# Generated by Django 2.2.4 on 2019-08-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(max_length=1500)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('size', models.CharField(choices=[('s', 'S'), ('m', 'M'), ('l', 'L'), ('vl', 'VL'), ('xl', 'XL'), ('26', 26), ('27', 27), ('28', 28), ('29', 29), ('30', 30), ('31', 31), ('32', 32), ('33', 33), ('34', 34), ('35', 35), ('36', 36), ('37', 37), ('38', 38), ('39', 39)], max_length=3)),
                ('color', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=200)),
                ('dress_type', models.CharField(choices=[('shirt', 'Shirt'), ('t-shirt', 'T-Shirt'), ('pants', 'Pants'), ('trousers', 'Trousers')], max_length=8)),
                ('quantity', models.IntegerField()),
                ('img', models.ImageField(upload_to='product-img')),
            ],
        ),
    ]
