# Generated by Django 2.2.4 on 2019-08-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20190806_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(default=None, upload_to='product-img'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='dress_type',
            field=models.CharField(choices=[('shirt', 'Shirt'), ('t-shirt', 'T-Shirt'), ('pants', 'Pants'), ('trousers', 'Trousers')], max_length=8),
        ),
    ]
